/**
 * BuildMart Comprehensive Mock Data
 * Used across all screens for demo/pitch purposes.
 * All prices in INR, all locations in Hyderabad.
 */

import { PRODUCT_IMAGES, WORKER_IMAGES, SHOP_IMAGES, BANNER_IMAGES, getProductImage } from './images';

// ─── Products ────────────────────────────────────────────────────────────────
export const MOCK_PRODUCTS = [
  {
    id: 'p1',
    name: 'UltraTech PPC Premium Cement',
    description: 'Portland Pozzolana Cement, ideal for slabs, columns & heavy foundations. 53 grade.',
    category: 'Cement',
    price: 385,
    unit: '50kg bag',
    inStock: true,
    stock: 240,
    badge: 'Best Seller',
    rating: 4.8,
    reviews: 2140,
    image: PRODUCT_IMAGES.cementBags,
    brand: 'UltraTech',
  },
  {
    id: 'p2',
    name: 'ACC Gold Water Shield Cement',
    description: 'Premium OPC 53 Grade with advanced water repellent technology.',
    category: 'Cement',
    price: 390,
    unit: '50kg bag',
    inStock: true,
    stock: 180,
    badge: null,
    rating: 4.6,
    reviews: 980,
    image: PRODUCT_IMAGES.cement,
    brand: 'ACC',
  },
  {
    id: 'p3',
    name: 'SAIL TMT Steel Bars Fe500D',
    description: 'High-strength TMT reinforcement bars, earthquake-resistant, 12mm diameter.',
    category: 'Steel',
    price: 72,
    unit: 'per kg',
    inStock: true,
    stock: 5000,
    badge: 'Best Seller',
    rating: 4.9,
    reviews: 1560,
    image: PRODUCT_IMAGES.steelBars,
    brand: 'SAIL',
  },
  {
    id: 'p4',
    name: 'Tata Tiscon TMT 10mm',
    description: 'Super ductile Fe500D grade, corrosion resistant. Perfect for beams & columns.',
    category: 'Steel',
    price: 75,
    unit: 'per kg',
    inStock: true,
    stock: 3200,
    badge: null,
    rating: 4.7,
    reviews: 890,
    image: PRODUCT_IMAGES.steelRods,
    brand: 'Tata',
  },
  {
    id: 'p5',
    name: 'Red Clay Bricks (Tandoor)',
    description: 'Premium kiln-fired red clay bricks, size 9×4.5×3 inches. Perfect finish.',
    category: 'Bricks',
    price: 7,
    unit: 'per brick',
    inStock: true,
    stock: 50000,
    badge: 'Popular',
    rating: 4.4,
    reviews: 620,
    image: PRODUCT_IMAGES.redBricks,
    brand: 'Local',
  },
  {
    id: 'p6',
    name: 'Fly Ash Bricks (Class A)',
    description: 'Eco-friendly, lighter weight, better thermal insulation than clay bricks.',
    category: 'Bricks',
    price: 6,
    unit: 'per brick',
    inStock: true,
    stock: 35000,
    badge: 'Eco Choice',
    rating: 4.5,
    reviews: 340,
    image: PRODUCT_IMAGES.brickWall,
    brand: 'GreenBuild',
  },
  {
    id: 'p7',
    name: 'Asian Paints Apex Ultima',
    description: 'Exterior emulsion paint with WeatherProof technology. 20 litre bucket.',
    category: 'Paint',
    price: 3400,
    unit: '20L bucket',
    inStock: true,
    stock: 85,
    badge: null,
    rating: 4.7,
    reviews: 1120,
    image: PRODUCT_IMAGES.paint,
    brand: 'Asian Paints',
  },
  {
    id: 'p8',
    name: 'Berger WeatherCoat All Guard',
    description: 'Elastomeric coating for maximum exterior weather protection. 10L pack.',
    category: 'Paint',
    price: 2200,
    unit: '10L bucket',
    inStock: true,
    stock: 60,
    badge: 'New Arrival',
    rating: 4.5,
    reviews: 280,
    image: PRODUCT_IMAGES.paintBuckets,
    brand: 'Berger',
  },
  {
    id: 'p9',
    name: 'Astral CPVC Pipe 1 inch',
    description: 'FlowGuard Plus CPVC, suitable for hot & cold water. 3m length.',
    category: 'Pipes',
    price: 285,
    unit: 'per pipe',
    inStock: true,
    stock: 420,
    badge: 'Best Seller',
    rating: 4.6,
    reviews: 450,
    image: PRODUCT_IMAGES.pvcPipes,
    brand: 'Astral',
  },
  {
    id: 'p10',
    name: 'Supreme uPVC Column Pipe',
    description: '110mm dia x 6m length. For borewell pumps. ISI marked.',
    category: 'Pipes',
    price: 1800,
    unit: 'per pipe',
    inStock: true,
    stock: 80,
    badge: null,
    rating: 4.3,
    reviews: 180,
    image: PRODUCT_IMAGES.pipes,
    brand: 'Supreme',
  },
  {
    id: 'p11',
    name: 'Havells HRFR Cable 2.5mm',
    description: 'Heat-resistant flame-retardant house wire. 90m coil. Red/Blue/Yellow.',
    category: 'Electrical',
    price: 2200,
    unit: 'per coil',
    inStock: true,
    stock: 150,
    badge: 'Popular',
    rating: 4.8,
    reviews: 720,
    image: PRODUCT_IMAGES.cables,
    brand: 'Havells',
  },
  {
    id: 'p12',
    name: 'Finolex FR Wire 1.5mm',
    description: 'Flame-retardant PVC insulated wire. 90 meters. Eco-friendly.',
    category: 'Electrical',
    price: 1650,
    unit: 'per coil',
    inStock: true,
    stock: 200,
    badge: null,
    rating: 4.5,
    reviews: 390,
    image: PRODUCT_IMAGES.wires,
    brand: 'Finolex',
  },
  {
    id: 'p13',
    name: 'River Sand (Grade 1)',
    description: 'Clean washed river sand, ideal for plastering & concrete work. Delivered in truck.',
    category: 'Sand & Aggregate',
    price: 1800,
    unit: 'per tonne',
    inStock: true,
    stock: 100,
    badge: null,
    rating: 4.2,
    reviews: 210,
    image: PRODUCT_IMAGES.sand,
    brand: 'Local',
  },
  {
    id: 'p14',
    name: 'M-Sand (Manufactured Sand)',
    description: 'IS 383 compliant manufactured sand. Zero silt. Better than river sand.',
    category: 'Sand & Aggregate',
    price: 1200,
    unit: 'per tonne',
    inStock: true,
    stock: 200,
    badge: 'Eco Choice',
    rating: 4.4,
    reviews: 160,
    image: PRODUCT_IMAGES.gravel,
    brand: 'BuildAggregates',
  },
  {
    id: 'p15',
    name: 'Sintex LOFT Water Tank 1000L',
    description: 'Triple layer insulated tank, UV-stabilised. Anti-microbial inner surface.',
    category: 'Hardware',
    price: 8200,
    unit: 'per unit',
    inStock: true,
    stock: 25,
    badge: 'Best Seller',
    rating: 4.7,
    reviews: 890,
    image: PRODUCT_IMAGES.waterTank,
    brand: 'Sintex',
  },
];

// ─── Categories ──────────────────────────────────────────────────────────────
export const MOCK_CATEGORIES = [
  { id: 'c1', name: 'Cement', icon: 'cube' as const, color: '#EF4444', count: 12 },
  { id: 'c2', name: 'Steel', icon: 'hardware-chip' as const, color: '#8B5CF6', count: 8 },
  { id: 'c3', name: 'Bricks', icon: 'grid' as const, color: '#F59E0B', count: 6 },
  { id: 'c4', name: 'Paint', icon: 'color-palette' as const, color: '#10B981', count: 15 },
  { id: 'c5', name: 'Pipes', icon: 'water' as const, color: '#3B82F6', count: 10 },
  { id: 'c6', name: 'Electrical', icon: 'flash' as const, color: '#F97316', count: 18 },
  { id: 'c7', name: 'Sand & Aggregate', icon: 'layers' as const, color: '#6366F1', count: 5 },
  { id: 'c8', name: 'Hardware', icon: 'construct' as const, color: '#EC4899', count: 22 },
];

// ─── Workers ─────────────────────────────────────────────────────────────────
export const MOCK_WORKERS = [
  {
    id: 'w1',
    name: 'Ramesh Kumar',
    skill: 'Mason',
    skills: ['Mason', 'Helper'],
    dailyRate: 800,
    rating: 4.8,
    jobs: 142,
    experience: 8,
    status: 'available',
    verified: true,
    location: 'Kukatpally, Hyderabad',
    image: WORKER_IMAGES.worker1,
    bio: 'Expert mason with 8 years of experience in RCC construction, brick laying, and plastering. Completed 140+ projects across Hyderabad.',
  },
  {
    id: 'w2',
    name: 'Venkatesh Reddy',
    skill: 'Electrician',
    skills: ['Electrician', 'Wireman'],
    dailyRate: 1200,
    rating: 4.9,
    jobs: 89,
    experience: 6,
    status: 'available',
    verified: true,
    location: 'Ameerpet, Hyderabad',
    image: WORKER_IMAGES.worker2,
    bio: 'Licensed electrician specializing in residential and commercial wiring. ITI certified. Available for full projects.',
  },
  {
    id: 'w3',
    name: 'Suresh Naidu',
    skill: 'Plumber',
    skills: ['Plumber', 'Helper'],
    dailyRate: 900,
    rating: 4.6,
    jobs: 67,
    experience: 5,
    status: 'working',
    verified: true,
    location: 'Madhapur, Hyderabad',
    image: WORKER_IMAGES.worker3,
    bio: 'Experienced plumber for all types of plumbing work including water supply, drainage, and bathroom fittings.',
  },
  {
    id: 'w4',
    name: 'Prasad Varma',
    skill: 'Carpenter',
    skills: ['Carpenter', 'Welder'],
    dailyRate: 1100,
    rating: 4.7,
    jobs: 112,
    experience: 10,
    status: 'available',
    verified: true,
    location: 'Secunderabad',
    image: WORKER_IMAGES.worker4,
    bio: 'Master carpenter with expertise in furniture making, door/window fitting, and wooden flooring installation.',
  },
  {
    id: 'w5',
    name: 'Kiran Babu',
    skill: 'Painter',
    skills: ['Painter'],
    dailyRate: 750,
    rating: 4.5,
    jobs: 45,
    experience: 4,
    status: 'available',
    verified: false,
    location: 'LB Nagar, Hyderabad',
    image: WORKER_IMAGES.worker5,
    bio: 'Professional painter specializing in interior and exterior painting, texture work, and waterproofing.',
  },
  {
    id: 'w6',
    name: 'Mohammed Gouse',
    skill: 'Welder',
    skills: ['Welder', 'Fabricator'],
    dailyRate: 1000,
    rating: 4.8,
    jobs: 78,
    experience: 7,
    status: 'available',
    verified: true,
    location: 'Tolichowki, Hyderabad',
    image: WORKER_IMAGES.worker6,
    bio: 'Skilled welder for steel gates, grills, railings and structural steel fabrication. Arc and MIG welding expert.',
  },
  {
    id: 'w7',
    name: 'Srinivas Goud',
    skill: 'Helper',
    skills: ['Helper', 'Mason'],
    dailyRate: 550,
    rating: 4.3,
    jobs: 34,
    experience: 2,
    status: 'available',
    verified: false,
    location: 'Dilsukhnagar, Hyderabad',
    image: WORKER_IMAGES.worker7,
    bio: 'Reliable construction helper for material handling, digging, cleaning, and general site assistance.',
  },
  {
    id: 'w8',
    name: 'Nagaraju Pillai',
    skill: 'Mason',
    skills: ['Mason', 'Plasterer'],
    dailyRate: 850,
    rating: 4.6,
    jobs: 98,
    experience: 9,
    status: 'working',
    verified: true,
    location: 'KPHB Colony, Hyderabad',
    image: WORKER_IMAGES.worker8,
    bio: 'Experienced mason and plasterer. Specializes in AAC block work, plastering, waterproofing, and tiling.',
  },
];

// ─── Shops ───────────────────────────────────────────────────────────────────
export const MOCK_SHOPS = [
  {
    id: 's1',
    name: 'Sri Venkat Building Materials',
    address: 'Plot 45, KPHB Colony Phase 1, Kukatpally, Hyderabad - 500072',
    rating: 4.7,
    reviews: 892,
    deliveryTime: '2-4 hours',
    minOrder: 500,
    image: SHOP_IMAGES.buildingMaterials,
    categories: ['Cement', 'Steel', 'Sand'],
    isOpen: true,
  },
  {
    id: 's2',
    name: 'Balaji Hardware & Paints',
    address: 'Door No 12-3-456, Ameerpet Main Road, Hyderabad - 500038',
    rating: 4.5,
    reviews: 430,
    deliveryTime: '3-5 hours',
    minOrder: 300,
    image: SHOP_IMAGES.hardwareStore,
    categories: ['Paint', 'Hardware', 'Tools'],
    isOpen: true,
  },
  {
    id: 's3',
    name: 'Anand Pipes & Electricals',
    address: 'Shop 7, Ameerpet Junction, Hyderabad - 500016',
    rating: 4.6,
    reviews: 280,
    deliveryTime: '1-3 hours',
    minOrder: 200,
    image: SHOP_IMAGES.electricalShop,
    categories: ['Pipes', 'Electrical', 'Fittings'],
    isOpen: true,
  },
];

// ─── Orders ──────────────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  {
    id: 'ord1',
    order_number: 'BM-2024-98234',
    shop: { name: 'Sri Venkat Building Materials' },
    status: 'delivered',
    total_amount: 24839,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: { name: 'UltraTech PPC Cement' }, quantity: 50, price: 385 },
      { product: { name: 'SAIL TMT Steel 12mm' }, quantity: 100, price: 72 },
    ],
    delivery_address: 'Flat 3B, Vasavi Apartments, Madhapur, Hyderabad',
  },
  {
    id: 'ord2',
    order_number: 'BM-2024-98235',
    shop: { name: 'Balaji Hardware & Paints' },
    status: 'out_for_delivery',
    total_amount: 6800,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: { name: 'Asian Paints Apex Ultima' }, quantity: 2, price: 3400 },
    ],
    delivery_address: 'Plot 22, Jubilee Hills, Hyderabad',
  },
  {
    id: 'ord3',
    order_number: 'BM-2024-98236',
    shop: { name: 'Anand Pipes & Electricals' },
    status: 'processing',
    total_amount: 4250,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: { name: 'Astral CPVC Pipe 1 inch' }, quantity: 10, price: 285 },
      { product: { name: 'Havells HRFR Cable 2.5mm' }, quantity: 1, price: 2200 },
    ],
    delivery_address: 'H.No 7-2-98, Ameerpet, Hyderabad',
  },
  {
    id: 'ord4',
    order_number: 'BM-2024-98220',
    shop: { name: 'Sri Venkat Building Materials' },
    status: 'cancelled',
    total_amount: 11500,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: { name: 'River Sand Grade 1' }, quantity: 5, price: 1800 },
      { product: { name: 'M-Sand' }, quantity: 1, price: 1200 },
    ],
    delivery_address: 'Road No 12, Banjara Hills, Hyderabad',
  },
  {
    id: 'ord5',
    order_number: 'BM-2024-98190',
    shop: { name: 'Sri Venkat Building Materials' },
    status: 'delivered',
    total_amount: 18200,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { product: { name: 'ACC Gold Cement' }, quantity: 30, price: 390 },
      { product: { name: 'Fly Ash Bricks' }, quantity: 1000, price: 6 },
      { product: { name: 'River Sand' }, quantity: 2, price: 1800 },
    ],
    delivery_address: 'Flat 3B, Vasavi Apartments, Madhapur, Hyderabad',
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────
export const MOCK_TRANSACTIONS = [
  { id: 't1', type: 'deposit', amount: 20000, description: 'Added money to wallet', date: '2024-11-01', isCredit: true, status: 'completed' },
  { id: 't2', type: 'payment', amount: 24839, description: 'Payment for Order BM-2024-98234', date: '2024-10-28', isCredit: false, status: 'completed' },
  { id: 't3', type: 'hold', amount: 6800, description: 'Escrow hold for Order BM-2024-98235', date: '2024-10-30', isCredit: false, status: 'held' },
  { id: 't4', type: 'payment', amount: 4250, description: 'Payment for Order BM-2024-98236', date: '2024-11-02', isCredit: false, status: 'completed' },
  { id: 't5', type: 'deposit', amount: 50000, description: 'Added money to wallet', date: '2024-10-20', isCredit: true, status: 'completed' },
  { id: 't6', type: 'release', amount: 18000, description: 'Released escrow — Labor job by Ramesh Kumar', date: '2024-10-15', isCredit: true, status: 'completed' },
  { id: 't7', type: 'hold', amount: 12000, description: 'Escrow hold for Agreement AGR-2024-001', date: '2024-10-10', isCredit: false, status: 'held' },
  { id: 't8', type: 'withdrawal', amount: 10000, description: 'Withdrawal to bank account', date: '2024-10-05', isCredit: false, status: 'completed' },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  { id: 'n1', type: 'order', title: 'Order Out for Delivery!', message: 'Your order BM-2024-98235 is on the way. Expected by 5:00 PM.', time: '2 min ago', read: false, icon: 'car-outline' as const, color: '#3B82F6' },
  { id: 'n2', type: 'payment', title: 'Payment Successful', message: '₹24,839 debited for Order BM-2024-98234. Thank you!', time: '1 hour ago', read: false, icon: 'checkmark-circle-outline' as const, color: '#10B981' },
  { id: 'n3', type: 'agreement', title: 'Agreement Signed', message: 'Ramesh Kumar has signed Agreement AGR-2024-001. Work begins tomorrow.', time: '3 hours ago', read: true, icon: 'document-text-outline' as const, color: '#8B5CF6' },
  { id: 'n4', type: 'worker', title: 'New Job Request', message: 'You have a new job request from Tarun C. for 5 days at ₹800/day.', time: 'Yesterday', read: true, icon: 'person-add-outline' as const, color: '#F59E0B' },
  { id: 'n5', type: 'order', title: 'Order Delivered!', message: 'Order BM-2024-98234 has been delivered successfully. Rate your experience.', time: 'Yesterday', read: true, icon: 'bag-check-outline' as const, color: '#10B981' },
  { id: 'n6', type: 'system', title: 'KYC Verification Approved', message: 'Your shopkeeper KYC has been verified. Your shop is now live on BuildMart!', time: '2 days ago', read: true, icon: 'shield-checkmark-outline' as const, color: '#6366F1' },
  { id: 'n7', type: 'payment', title: 'Money Added to Wallet', message: '₹20,000 has been added to your BuildMart wallet.', time: '3 days ago', read: true, icon: 'wallet-outline' as const, color: '#10B981' },
  { id: 'n8', type: 'order', title: 'Order Confirmed', message: 'Sri Venkat Building Materials confirmed your order BM-2024-98234.', time: '5 days ago', read: true, icon: 'storefront-outline' as const, color: '#F97316' },
];

// ─── Agreements ───────────────────────────────────────────────────────────────
export const MOCK_AGREEMENTS = [
  {
    id: 'agr1',
    number: 'AGR-2024-001',
    title: 'Bricklaying & Plastering Work',
    contractor: { name: 'Tarun Reddy', company: 'TRC Constructions' },
    worker: { name: 'Ramesh Kumar', skill: 'Mason' },
    status: 'active',
    duration: 20,
    startDate: '2024-11-01',
    endDate: '2024-11-20',
    dailyRate: 800,
    totalAmount: 16000,
    location: 'Plot 22, Jubilee Hills, Hyderabad',
    description: 'Complete bricklaying and plastering for G+2 residential building.',
    contractorSigned: true,
    workerSigned: true,
  },
  {
    id: 'agr2',
    number: 'AGR-2024-002',
    title: 'Electrical Wiring & Panel Setup',
    contractor: { name: 'Vijay Kumar', company: 'VK Infrastructure' },
    worker: { name: 'Venkatesh Reddy', skill: 'Electrician' },
    status: 'pending_signature',
    duration: 10,
    startDate: '2024-11-05',
    endDate: '2024-11-14',
    dailyRate: 1200,
    totalAmount: 12000,
    location: 'Gachibowli IT Hub, Hyderabad',
    description: 'Complete electrical wiring for 3-floor commercial building including panel setup.',
    contractorSigned: true,
    workerSigned: false,
  },
  {
    id: 'agr3',
    number: 'AGR-2024-003',
    title: 'Interior Painting - 3BHK',
    contractor: { name: 'Ravi Shankar', company: 'RS Projects' },
    worker: { name: 'Kiran Babu', skill: 'Painter' },
    status: 'completed',
    duration: 7,
    startDate: '2024-10-10',
    endDate: '2024-10-16',
    dailyRate: 750,
    totalAmount: 5250,
    location: 'Kondapur, Hyderabad',
    description: 'Interior painting for 3BHK apartment including texture work in living room.',
    contractorSigned: true,
    workerSigned: true,
  },
];

// ─── Deliveries ───────────────────────────────────────────────────────────────
export const MOCK_DELIVERIES = [
  {
    id: 'd1',
    orderId: 'ord2',
    orderNumber: 'BM-2024-98235',
    pickupAddress: 'Sri Venkat Building Materials, KPHB Colony, Kukatpally',
    dropAddress: 'Plot 22, Jubilee Hills, Hyderabad',
    items: '2x Asian Paints Apex 20L',
    distance: '8.2 km',
    eta: '35 min',
    payout: 150,
    status: 'accepted',
    customer: { name: 'Tarun Chintakunta', phone: '+91 90000 00001' },
  },
  {
    id: 'd2',
    orderId: 'ord3',
    orderNumber: 'BM-2024-98236',
    pickupAddress: 'Anand Pipes & Electricals, Ameerpet Junction',
    dropAddress: 'H.No 7-2-98, Ameerpet, Hyderabad',
    items: '10x CPVC Pipes, 1x Havells Cable',
    distance: '2.1 km',
    eta: '12 min',
    payout: 80,
    status: 'available',
    customer: { name: 'Raj Kumar', phone: '+91 98765 43210' },
  },
  {
    id: 'd3',
    orderId: 'ord6',
    orderNumber: 'BM-2024-98240',
    pickupAddress: 'Balaji Hardware, Ameerpet Main Road',
    dropAddress: 'Road No 12, Banjara Hills, Hyderabad',
    items: '15x Bricks bags, 2x Sand bags',
    distance: '5.8 km',
    eta: '28 min',
    payout: 120,
    status: 'available',
    customer: { name: 'Priya Sharma', phone: '+91 87654 32109' },
  },
];

// ─── Admin Stats ──────────────────────────────────────────────────────────────
export const ADMIN_STATS = {
  totalUsers: 1247,
  newUsersToday: 12,
  activeOrders: 89,
  gmvToday: 421500,
  gmvThisMonth: 12450000,
  pendingKyc: 23,
  platformRevenueMonth: 124500,
  totalShops: 48,
  totalWorkers: 312,
  totalDrivers: 67,
};

export const ADMIN_GMV_WEEKLY = [
  { day: 'Mon', amount: 380000 },
  { day: 'Tue', amount: 520000 },
  { day: 'Wed', amount: 290000 },
  { day: 'Thu', amount: 680000 },
  { day: 'Fri', amount: 890000 },
  { day: 'Sat', amount: 1100000 },
  { day: 'Sun', amount: 421500 },
];

export const PENDING_VERIFICATIONS = [
  { id: 'v1', name: 'Ravi Kiran', phone: '9876543210', role: 'shopkeeper', submittedAt: '2 hours ago', documents: ['Aadhaar', 'PAN', 'GST Certificate'] },
  { id: 'v2', name: 'Sunita Devi', phone: '8765432109', role: 'worker', submittedAt: '4 hours ago', documents: ['Aadhaar', 'Skill Certificate'] },
  { id: 'v3', name: 'Mohammed Irfan', phone: '7654321098', role: 'driver', submittedAt: '6 hours ago', documents: ['Aadhaar', 'Driving License', 'Vehicle RC'] },
  { id: 'v4', name: 'Laxmi Prasad', phone: '6543210987', role: 'shopkeeper', submittedAt: 'Yesterday', documents: ['Aadhaar', 'PAN', 'Business License'] },
  { id: 'v5', name: 'Ganesh Babu', phone: '9988776655', role: 'worker', submittedAt: 'Yesterday', documents: ['Aadhaar', 'ITI Certificate'] },
];
